"""make_licencia_categoria_nullable_in_choferes

Revision ID: 26852aca55d4
Revises: af96ee22753c
Create Date: 2026-09-17 17:15:59.126320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26852aca55d4'
down_revision: Union[str, Sequence[str], None] = 'af96ee22753c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
