"""make_licencia_categoria_nullable_in_choferes

Revision ID: 2f3fabf8f99f
Revises: 26852aca55d4
Create Date: 2026-09-17 17:26:35.293451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f3fabf8f99f'
down_revision: Union[str, Sequence[str], None] = '26852aca55d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('choferes', 'licencia',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('choferes', 'categoria',
               existing_type=postgresql.ENUM('A', 'B', 'C', name='categoriaenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('choferes', 'categoria',
               existing_type=postgresql.ENUM('A', 'B', 'C', name='categoriaenum'),
               nullable=False)
    op.alter_column('choferes', 'licencia',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
