"""add gmail to persons, remove email from users

Revision ID: 5f5d1ca0b335
Revises: bc4d2f1a9c3e
Create Date: 2026-06-21 12:15:30.195917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5d1ca0b335'
down_revision: Union[str, Sequence[str], None] = 'bc4d2f1a9c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('gmail', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'persons', ['gmail'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'persons', type_='unique')
    op.drop_column('persons', 'gmail')
    # ### end Alembic commands ###
