"""create_camiones_table

Revision ID: 6b904d0d4643
Revises: db399e0f3f66
Create Date: 2026-07-21 18:55:57.821506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b904d0d4643'
down_revision: Union[str, Sequence[str], None] = 'db399e0f3f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('capacidad_carga_kg', sa.Float(), nullable=False),
    sa.Column('volumen_capacity_m3', sa.Float(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('numero_chasis', sa.String(length=100), nullable=False),
    sa.Column('numero_motor', sa.String(length=100), nullable=False),
    sa.Column('vencimiento_soat', sa.Date(), nullable=False),
    sa.Column('vencimiento_inspeccion_tecnica', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_chasis'),
    sa.UniqueConstraint('numero_motor'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_camiones_id'), 'camiones', ['id'], unique=False)
    op.add_column('images', sa.Column('camion_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'images', ['camion_id'])
    op.create_foreign_key(None, 'images', 'camiones', ['camion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'camion_id')
    op.drop_index(op.f('ix_camiones_id'), table_name='camiones')
    op.drop_table('camiones')
    # ### end Alembic commands ###
