"""add is_active to taller_mecanico

Revision ID: 80c533d09d4d
Revises: 9ceb507ebcef
Create Date: 2026-07-27 22:46:17.236911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c533d09d4d'
down_revision: Union[str, Sequence[str], None] = '9ceb507ebcef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taller_mecanico', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taller_mecanico', 'is_active')
    # ### end Alembic commands ###
