"""add is_active to repuestos

Revision ID: 8916d6fd28ea
Revises: 4d164abf54ff
Create Date: 2026-07-28 21:40:22.733267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8916d6fd28ea'
down_revision: Union[str, Sequence[str], None] = '4d164abf54ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repuestos', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repuestos', 'is_active')
    # ### end Alembic commands ###
