"""create_servicio_mecanico_tables

Revision ID: 9ceb507ebcef
Revises: d6532e1f3ddd
Create Date: 2026-07-23 00:10:30.234258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ceb507ebcef'
down_revision: Union[str, Sequence[str], None] = 'd6532e1f3ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repuestos_id'), 'repuestos', ['id'], unique=False)
    op.create_table('taller_mecanico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taller_mecanico_id'), 'taller_mecanico', ['id'], unique=False)
    op.create_table('tipo_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_servicio_id'), 'tipo_servicio', ['id'], unique=False)
    op.create_table('servicio_mecanico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camion_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('mano_obra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_repuestos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camion_id'], ['camiones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taller_id'], ['taller_mecanico.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_servicio_id'], ['tipo_servicio.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicio_mecanico_id'), 'servicio_mecanico', ['id'], unique=False)
    op.create_table('detalle_repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mantenimiento_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['servicio_mecanico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_repuesto_id'), 'detalle_repuesto', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_repuesto_id'), table_name='detalle_repuesto')
    op.drop_table('detalle_repuesto')
    op.drop_index(op.f('ix_servicio_mecanico_id'), table_name='servicio_mecanico')
    op.drop_table('servicio_mecanico')
    op.drop_index(op.f('ix_tipo_servicio_id'), table_name='tipo_servicio')
    op.drop_table('tipo_servicio')
    op.drop_index(op.f('ix_taller_mecanico_id'), table_name='taller_mecanico')
    op.drop_table('taller_mecanico')
    op.drop_index(op.f('ix_repuestos_id'), table_name='repuestos')
    op.drop_table('repuestos')
    # ### end Alembic commands ###
