"""move_fk_user_id_from_persons_to_users

Revision ID: aacbe36e4512
Revises: b31fd9cc5b37
Create Date: 2026-06-24 16:53:51.520955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacbe36e4512'
down_revision: Union[str, Sequence[str], None] = 'b31fd9cc5b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['person_id'])
    op.create_foreign_key(None, 'users', 'persons', ['person_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'person_id')
    # ### end Alembic commands ###
