"""create_ubicacion_gps_table

Revision ID: af96ee22753c
Revises: e8948279d615
Create Date: 2026-09-02 16:25:51.625996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af96ee22753c'
down_revision: Union[str, Sequence[str], None] = 'e8948279d615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubicacion_gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_servicio_transporte', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('velocidad', sa.Float(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio_transporte'], ['servicio_transporte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ubicacion_gps_fecha_hora'), 'ubicacion_gps', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_ubicacion_gps_id'), 'ubicacion_gps', ['id'], unique=False)
    op.create_index(op.f('ix_ubicacion_gps_id_servicio_transporte'), 'ubicacion_gps', ['id_servicio_transporte'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ubicacion_gps_id_servicio_transporte'), table_name='ubicacion_gps')
    op.drop_index(op.f('ix_ubicacion_gps_id'), table_name='ubicacion_gps')
    op.drop_index(op.f('ix_ubicacion_gps_fecha_hora'), table_name='ubicacion_gps')
    op.drop_table('ubicacion_gps')
    # ### end Alembic commands ###
