"""create_ruta_tables

Revision ID: ce247d64f266
Revises: ee4202878076
Create Date: 2026-08-03 23:03:18.173900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce247d64f266'
down_revision: Union[str, Sequence[str], None] = 'ee4202878076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('punto_carga_combustible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punto_carga_combustible_id'), 'punto_carga_combustible', ['id'], unique=False)
    op.create_table('punto_peaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punto_peaje_id'), 'punto_peaje', ['id'], unique=False)
    op.create_table('ruta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('ciudad_origen', sa.String(length=50), nullable=False),
    sa.Column('ciudad_destino', sa.String(length=50), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado', sa.Float(), nullable=True),
    sa.Column('tipo_de_via', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruta_id'), 'ruta', ['id'], unique=False)
    op.create_table('ruta_peajes',
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.Column('punto_peaje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_peaje_id'], ['punto_peaje.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruta_id'], ['ruta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ruta_id', 'punto_peaje_id')
    )
    op.create_table('ruta_puntos_carga',
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.Column('punto_carga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_carga_id'], ['punto_carga_combustible.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruta_id'], ['ruta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ruta_id', 'punto_carga_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruta_puntos_carga')
    op.drop_table('ruta_peajes')
    op.drop_index(op.f('ix_ruta_id'), table_name='ruta')
    op.drop_table('ruta')
    op.drop_index(op.f('ix_punto_peaje_id'), table_name='punto_peaje')
    op.drop_table('punto_peaje')
    op.drop_index(op.f('ix_punto_carga_combustible_id'), table_name='punto_carga_combustible')
    op.drop_table('punto_carga_combustible')
    # ### end Alembic commands ###
