"""make_person_id_nullable_in_images

Revision ID: d6532e1f3ddd
Revises: 6b904d0d4643
Create Date: 2026-07-21 19:17:50.552484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6532e1f3ddd'
down_revision: Union[str, Sequence[str], None] = '6b904d0d4643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
