"""create_servicio_transporte_tables

Revision ID: da5aab8fe518
Revises: e4cb932d8cd3
Create Date: 2026-08-11 16:50:36.638730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5aab8fe518'
down_revision: Union[str, Sequence[str], None] = 'e4cb932d8cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punto_carga', sa.String(length=255), nullable=False),
    sa.Column('punto_descarga', sa.String(length=255), nullable=False),
    sa.Column('viaticos_chofer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('viaticos_ayudante', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('combustible', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('PROGRAMADO', 'EN_CURSO', 'FINALIZADO', 'CANCELADO', name='estadoservicioenum'), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_usuario_sistema', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=False),
    sa.Column('id_camion', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_camion'], ['camiones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_ruta'], ['ruta.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario_sistema'], ['user_system.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicio_transporte_id'), 'servicio_transporte', ['id'], unique=False)
    op.create_table('servicio_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_servicio_transporte', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('peso_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumen_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_servicio_transporte'], ['servicio_transporte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicio_cliente_id'), 'servicio_cliente', ['id'], unique=False)
    op.create_table('informacion_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peso_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumen_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peso', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumen', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_servicio_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio_cliente'], ['servicio_cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_informacion_carga_id'), 'informacion_carga', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_informacion_carga_id'), table_name='informacion_carga')
    op.drop_table('informacion_carga')
    op.drop_index(op.f('ix_servicio_cliente_id'), table_name='servicio_cliente')
    op.drop_table('servicio_cliente')
    op.drop_index(op.f('ix_servicio_transporte_id'), table_name='servicio_transporte')
    op.drop_table('servicio_transporte')
    # ### end Alembic commands ###
