"""add_is_active_to_punto_carga_combustible

Revision ID: e4cb932d8cd3
Revises: ddf2456983a6
Create Date: 2026-08-04 15:01:37.895852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cb932d8cd3'
down_revision: Union[str, Sequence[str], None] = 'ddf2456983a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punto_carga_combustible', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('punto_peaje', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('punto_peaje', 'is_active')
    op.drop_column('punto_carga_combustible', 'is_active')
    # ### end Alembic commands ###
