"""create_choferes_table

Revision ID: e773b85f9262
Revises: 77674fb49d54
Create Date: 2026-07-20 17:34:10.162972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e773b85f9262'
down_revision: Union[str, Sequence[str], None] = '77674fb49d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choferes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('licencia', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.Enum('A', 'B', 'C', name='categoriaenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licencia'),
    sa.UniqueConstraint('person_id')
    )
    op.create_index(op.f('ix_choferes_id'), 'choferes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_choferes_id'), table_name='choferes')
    op.drop_table('choferes')
    # ### end Alembic commands ###
