"""add_motivo_cancelacion_to_servicio_transporte

Revision ID: e8948279d615
Revises: da5aab8fe518
Create Date: 2026-09-02 08:02:16.378924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8948279d615'
down_revision: Union[str, Sequence[str], None] = 'da5aab8fe518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio_transporte', sa.Column('motivo_cancelacion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio_transporte', 'motivo_cancelacion')
    # ### end Alembic commands ###
