"""add is_active to tipo_servicio

Revision ID: ee4202878076
Revises: 8916d6fd28ea
Create Date: 2026-07-28 21:54:57.488725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4202878076'
down_revision: Union[str, Sequence[str], None] = '8916d6fd28ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_servicio', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_servicio', 'is_active')
    # ### end Alembic commands ###
