"""create_clients_table

Revision ID: fd824e80da37
Revises: aacbe36e4512
Create Date: 2026-07-17 10:10:03.992175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd824e80da37'
down_revision: Union[str, Sequence[str], None] = 'aacbe36e4512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('persons_user_id_key'), 'persons', type_='unique')
    op.drop_constraint(op.f('persons_user_id_fkey'), 'persons', type_='foreignkey')
    op.drop_column('persons', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('persons_user_id_fkey'), 'persons', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('persons_user_id_key'), 'persons', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
